Hazelcast.Net/Hazelcast.Core/HazelcastException.cs, Hazelcast.Net/Hazelcast.Util/ClientExceptionFactory.cs, Hazelcast.Test/Hazelcast.Client.Test/ClientRingbufferTest.cs
Exception is thrown when the read sequence is less than the head sequence.
=> Add StaleSequenceException for Ringbuffer 

Hazelcast.Net/Hazelcast.Client.Proxy/ClientMapProxy.cs, Hazelcast.Net/Hazelcast.Client/ClientNearCache.cs, Hazelcast.Net/Hazelcast.Config/InMemoryFormat.cs, Hazelcast.Test/Hazelcast.Client.Test/ClientNearCacheTest.cs, Hazelcast.Test/Hazelcast.Client.Test/HazelcastNode.cs
* When maximum size is reached, the eviction function should evict items according to policy
* On Map.Get() the deserialised result should be stored in the cache
* On Map.GetAll it should not remove items from the collection it is iterating on
* EntryEvents should be handled according to their type
* Disabled Offheap in memory format as it is not supported
* Add several tests for all of the above
=> Fixed several issues with ClientNearCache

Hazelcast.Net/Hazelcast.IO.Serialization/ByteArraySerializerAdapter.cs, Hazelcast.Net/Hazelcast.IO.Serialization/ConstantSerializers.cs, Hazelcast.Net/Hazelcast.IO.Serialization/DefaultSerializers.cs, Hazelcast.Net/Hazelcast.IO.Serialization/SerializationConstants.cs, Hazelcast.Net/Hazelcast.IO.Serialization/SerializationService.cs, Hazelcast.Net/Hazelcast.IO.Serialization/SerializationServiceBuilder.cs, Hazelcast.Net/Hazelcast.IO.Serialization/StreamSerializerAdapter.cs, Hazelcast.Test/Hazelcast.Client.Test.Serialization/ConstantSerializerTest.cs
Update default serializers to be constant, and add serializers for List
and LinkedList
=> Update SerializationService to bring it in line with Java client

Hazelcast.Net/Hazelcast.Config/GlobalSerializerConfig.cs, Hazelcast.Net/Hazelcast.IO.Serialization/SerializationService.cs, Hazelcast.Net/Hazelcast.IO.Serialization/SerializationServiceBuilder.cs, Hazelcast.Test/Hazelcast.Client.Test.Serialization/ClientCustomSerializationTest.cs, Hazelcast.Test/Hazelcast.Test.csproj, build.bat
Global serializer should have lower priority than CLR serialization, unless
an override is specified.
=> Changes to bring serialization in order with the Java client

sonar-project.properties
The sonar propertıes fıle enables the sonar-runner.bat to be run on the windows machine.
=> Add sonar-project.properties for running sonar analysis

Hazelcast.Net/Hazelcast.IO.Serialization/SerializationService.cs, Hazelcast.Test/Hazelcast.Client.Test.Serialization/DataInputOutputTest.cs
The serialization of objects was not compatible between Java and C#
as the additional null flag for objects was removed from 3.6 in Java but
not from the C# client
Fixes #43
=> Fixed serialization compatibility issue between Java and C# client

Hazelcast.Net/Hazelcast.IO.Serialization/SerializationService.cs, Hazelcast.Test/Hazelcast.Client.Test.Serialization/DataInputOutputTest.cs
The serialization of objects was not compatible between Java and C#
as the additional null flag for objects was removed from 3.6 in Java but
not from the C# client
Fixes #43
=> [Backport] Fixed serialization compatibility issue between Java and C# client

Hazelcast.Net/Hazelcast.Client.Connection/ClientConnection.cs, Hazelcast.Net/Hazelcast.Client.Connection/ClientConnectionManager.cs, Hazelcast.Net/Hazelcast.Client.Spi/ClientClusterService.cs, Hazelcast.Test/Hazelcast.Client.Test/ClientReconnectionTest.cs
When owner connection drops, if another connection was already available 
it should be promoted to owner
=> Promote connections to owner connection if one was available

Hazelcast.Net/Hazelcast.Client.Spi/ProxyManager.cs, Hazelcast.Test/Hazelcast.Client.Test/ClientDistributedObjectTest.cs
When GetDistributedObjects() is called with existing objects created from
other clients, there would be an exception thrown if the proxy had
generic type arguments.
Now, proxies created through GetDistributedObjects() will have parameters
of type "Object", but can be recreated when asked for with a specific
generic type.
=> Fix for GetDistributedObjects()

Hazelcast.Net/Hazelcast.Client.Protocol/ClientMessage.cs
Backport from https://github.com/hazelcast/hazelcast/pull/7547 and https://github.com/hazelcast/hazelcast/pull/7550
fix #76
=> client message internal buffer created with correct size for decode

Hazelcast.Net/Hazelcast.Client.Connection/ClientConnection.cs
`SocketOptions.GetLingerSeconds()` is 3 seconds by default. Socket lingering can be disabled by entering zero value:
`SocketOptions.SetLingerSeconds(0)` -> disables socket lingering.
=> Disabling socket linger option is not working. 

Hazelcast.Net/Hazelcast.Client.Spi/ClientClusterService.cs, Hazelcast.Net/Hazelcast.Client.Spi/IClientClusterService.cs, Hazelcast.Net/Hazelcast.Util/AddressHelper.cs
=> fix connection address shuffling

Hazelcast.Net/Hazelcast.Client.Connection/ClientConnectionManager.cs
The values for timeout and interval are mixed up.
=> Fixes interval/heartbeat mixup in ClientConnectionManager

Hazelcast.Net/Hazelcast.Client.Proxy/ClientMapNearCacheProxy.cs, Hazelcast.Net/Hazelcast.Client.Proxy/ClientMapProxy.cs, Hazelcast.Net/Hazelcast.Client.Spi/ClientPartitionService.cs
Backport of #223
the partition update wait time for the first time is updated to 100ms from 10sec.
=> [Backport]GetAsync call removed redundant internal task creation

Hazelcast.Net/Hazelcast.Client.Connection/ClientConnection.cs
This PR changes the way `SSLProtocols` are resoled when no client-side certPath specified. Before this change, whenever the `certPath` was not specified the following methods was used:
```
sslStream.AuthenticateAsClient(certificateName);
```
which underneath delegates the selection to `ServicePointManager.DefaultSslProtocols`. This means that the user setting for the SSL/TLS protocol was ignored. With this change it always uses the value specified by the client.
Potentially this is a breaking change, as whenever the setting in Hazelcast settings was different from the ServicePointManager, it would impact the selection.
=> SSL setup should respect setting of the protocols 

Hazelcast.Net/Hazelcast.Client.Spi/ClientClusterService.cs, Hazelcast.Net/Hazelcast.IO/Address.cs, Hazelcast.Net/Hazelcast.Util/AddressUtil.cs, Hazelcast.Net/Hazelcast.Util/DnsUtil.cs, Hazelcast.Test/Hazelcast.Client.Test/DnsErrorsTest.cs, Hazelcast.Test/Overrides.cs
This PR addresses #240 
The fix is based on #233 
This PR introduces an additional layer for DNS probing that enables injecting faults to the resolution mechanism. With this it enables simulating DNS occasional problems.
`ConnectAsOwner` is fixed on basis of #233, by moving the `address.GetInetSocketAddress` to the inside of the `try` block.
I think that `GetPossibleIpAddressesFor` also is prone to throwing, but I'm not able to find the execution path that would fall into this category. Would be great if somebody could hive me a hint how to setup the configuration to make it fall. Now with DNS fault injection, it's easy when right params are known.
=> Handling DNS resolution failures gracefully

Hazelcast.Test/Hazelcast.Client.Test/VersionUtilTest.cs
This PR replaces an assert of not ending with `".0"` with an assert of a proper prefix for the obtained version.
=> VersionUtilTest fixed

Hazelcast.Examples/Hazelcast.Examples.csproj, Hazelcast.Net/Hazelcast.Config/SSLConfig.cs, Hazelcast.Net/Hazelcast.IO.Serialization/BufferPool.cs, Hazelcast.Net/Hazelcast.Net.csproj, Hazelcast.Test/Hazelcast.Client.Test.Serialization/BufferPoolTest.cs, Hazelcast.Test/Hazelcast.Client.Test/ClientHeartBeatDetailTest.cs, Hazelcast.Test/Hazelcast.Client.Test/ClientShutdownTest.cs, Hazelcast.Test/Hazelcast.Client.Test/TestSupport.cs, Hazelcast.Test/Hazelcast.Test.csproj, README.md, build.ps1
This PR moves the solution to `net45` to enable newer features of the runtime, packages and the C# language. Additionally:
- it makes `BufferPool` tests independent from the `GC.Collect` by spinning a test in a loop and checking with `GC.GetTotalMemory(true)` is the memory size breached
- it changes the implementation of the `BufferPoolThreadLocal` simpler, by switching to `ThreadLocal` only as in .NET `ThreadLocal` will not leak no matter if they are disposed or finalized (they have a proper `Dispose(bool)` implementation.
- it changes the behavior of the disposed `BufferPool`. Previously, it was possible to still obtain a buffer when the pool is disposed and the `WeakReference`'s target is not released yet. Currently, it will always throw an exception. This changes the type of exception …
=> Moving to net45

.nuget/packages.config, Hazelcast.Examples/Hazelcast.Examples.csproj, Hazelcast.Net.sln, Hazelcast.Net/Hazelcast.Net.csproj, Hazelcast.Test/Hazelcast.Test.csproj, Hazelcast.Test/Overrides.cs, build.proj, build.ps1, build.sh
~Creates a `Release-Build` configuration used by `build.ps1` - is identical to `Release` but the test project has extra dependencies for this configuration, eg the NUnit console runner, used by `build.ps1`.~
Removes the dependencies to `JetBrains.dotCover.CommandLineTools` and `NUnit.ConsoleRunner` from the test project and also removes the `.nuget/package.config` - instead, introduces a `build.proj` project file used by the `build.ps1` to explicitely restore these dependency packages when building. Cleaner and more explicit.
The `build.proj` project is *not* listed in the `.sln` file and therefore these packages are not restored by default.
Additionally, remove the NUnit 2.x output format, as Jenkins can now deal with NUnit 3.x - this needs to be configured for each Jenkins build. …
=> Fix build packages and NUnit version for Jenkins

hz.ps1, hz.sh
Includes:
* Ensure we can have TLS 1.2 even on old Windows 8.1 machines
* Ensure we use `pwsh` if available, before trying `powershell`
* Improve error messages if wrong versions of PowerShell or .NET were found
* Remove dependency on Maven to download artifacts
=> Various improvements to the build script

src/Hazelcast.Net.Testing/StringExtensions.cs, src/Hazelcast.Net.Testing/TestServer/Server.cs, src/Hazelcast.Net.Testing/TestServer/ServerSocketConnection.cs, src/Hazelcast.Net.Testing/TestServer/ServerSocketListener.cs, src/Hazelcast.Net.Tests/Clustering/OrphanSubscriptionTests.cs, src/Hazelcast.Net.Tests/Core/DistributedEventSchedulerTests.cs, src/Hazelcast.Net.Tests/Core/DumpCoreExtensionsTests.cs, src/Hazelcast.Net.Tests/Messaging/ClientMessageTests.cs, src/Hazelcast.Net.Tests/Messaging/DumpMessagingExtensionsTests.cs, src/Hazelcast.Net.Tests/Networking/NetworkingTests.cs, src/Hazelcast.Net.Tests/Testing/LoggingTests.cs, src/Hazelcast.Net/Clustering/ClusterConnections.cs, src/Hazelcast.Net/Clustering/ClusterEvents.cs, src/Hazelcast.Net/Clustering/ClusterState.cs, src/Hazelcast.Net/Clustering/ClusterSubscription.cs, src/Hazelcast.Net/Clustering/DistributedEventScheduler.cs, src/Hazelcast.Net/Clustering/IClusterOptions.cs, src/Hazelcast.Net/Clustering/MemberConnection.cs, src/Hazelcast.Net/Events/EventsOptions.cs, src/Hazelcast.Net/HazelcastOptions.ClusterOptions.cs, src/Hazelcast.Net/Messaging/ClientMessage.cs, src/Hazelcast.Net/Networking/ClientSocketConnection.cs
Add the ability to handled orphaned subscriptions: when a user unsubscribes from events, we try to remove the corresponding listener on each member. If that succeeds then all is well. Otherwise, we still return `true` but we keep the subscription around, and mark it as orphaned. If we receive an event from a member, corresponding to an orphaned subscription, we try again to remove the listener for that member. Eventually, the subscription should be removed.
There is a corresponding test that uses our testing server to verify that it works.
Now, events are triggered by actions... if a listener remains active on a member and we never trigger an action on that member, no event may be triggered and both the listener on the member, and the subscription on the client, will leak.
A next feature …
=> Handle orphaned subscriptions

src/Hazelcast.Net.Tests/Clustering/LoadBalancingTests.cs, src/Hazelcast.Net.Tests/Remote/ClientTxnListTest.cs, src/Hazelcast.Net.Tests/Remote/ClientTxnMultiMapTest.cs, src/Hazelcast.Net.Tests/Remote/ClientTxnSetTest.cs, src/Hazelcast.Net.Tests/Remote/TransactionTests.cs, src/Hazelcast.Net/Clustering/DistributedEventExceptionEventArgs.cs, src/Hazelcast.Net/Clustering/IClusterOptions.cs, src/Hazelcast.Net/Clustering/LoadBalancing/StaticLoadBalancer.cs, src/Hazelcast.Net/Configuration/ConfigurationBuilderExtensions.cs, src/Hazelcast.Net/DistributedObjects/CollectionItemEventArgs.cs, src/Hazelcast.Net/HazelcastOptions.ClusterOptions.cs, src/Hazelcast.Net/Projections/IProjection.cs, src/Hazelcast.Net/Projections/SingleAttributeProjection.cs, src/Hazelcast.Net/Security/KerberosCredentialsFactory.cs, src/Hazelcast.Net/Security/TokenCredentialsFactory.cs, src/Hazelcast.Net/Security/UsernamePasswordCredentialsFactory.cs, src/Hazelcast.Net/Transactions/ITransactionContext.cs, src/Hazelcast.Net/Transactions/TransactionContext.cs, src/Hazelcast.Net/Transactions/TransactionState.cs
(merge after #336)
HazelcastOptions#LoadBalancingOptions - default is RoundRobin
Hazelcast Security - make all credentials factory internals, they can be configured via shortcuts in the configuration file, or extension methods in the code
ITransactionContext#State - internal
TransactionState - internal
ITransactionContext - get rid of GetTransactionalAsync methods
StaticLoadBalancer - throws on NotifyMembers - fixed
ConfigurationBuilderExtensions - document AddHazelcastFile
There is a rendered X in this page. I suppose this should be the :x:y text instead. https://hazelcast.github.io/hazelcast-csharp-client/dev/api/Hazelcast.Configuration.ConfigurationBuilderExtensions.AddHazelcastCommandLine.html#Hazelcast_Configuration_ConfigurationBuilderExtensions_AddHazelcastCommandLine_Microsoft_Exte …
=> Cleanup after reviews

src/Hazelcast.Net.Benchmarks/Hazelcast.Net.Benchmarks.csproj, src/Hazelcast.Net.Benchmarks/ReadWriteUtf8.cs, src/Hazelcast.Net.Testing/Utf8Char.cs, src/Hazelcast.Net.Tests/Core/ByteExtensionsTests.cs, src/Hazelcast.Net.Tests/Serialization/StringSerializationTest.cs, src/Hazelcast.Net/Core/BytesExtensions.Protocol.cs, src/Hazelcast.Net/Core/BytesExtensions.ReadFromByteArray.cs, src/Hazelcast.Net/Core/BytesExtensions.ReadFromReadOnlySequence.cs, src/Hazelcast.Net/Core/BytesExtensions.ReadFromReadOnlySpan.cs, src/Hazelcast.Net/Core/BytesExtensions.WriteToByteArray.cs, src/Hazelcast.Net/Core/BytesExtensions.cs, src/Hazelcast.Net/Data/BitmapIndexOptions.cs, src/Hazelcast.Net/Data/EndpointQualifier.cs, src/Hazelcast.Net/Data/IndexOptions.cs, src/Hazelcast.Net/Data/IndexType.cs, src/Hazelcast.Net/Data/MemberInfo.cs, src/Hazelcast.Net/Data/ProtocolType.cs, src/Hazelcast.Net/Data/UniqueKeyTransformation.cs, src/Hazelcast.Net/NearCaching/EvictionPolicy.cs, src/Hazelcast.Net/NearCaching/LfuComparer.cs, src/Hazelcast.Net/NearCaching/NearCacheBase.cs, src/Hazelcast.Net/NearCaching/RandomComparer.cs, src/Hazelcast.Net/Properties/AssemblyInfo.cs, src/Hazelcast.Net/Serialization/ByteArrayObjectDataInput.cs, src/Hazelcast.Net/Serialization/ByteArrayObjectDataOutput.cs
IndexOptions - Equivalent of ValidateAttribute(IndexOptions, String) is private on Java.
ProtocolType - Related to advanced network configuration, can also be made private.
IndexType - There is no enum variant for Bitmap indexes - added
BytesExtensions - I believe we don't expose buffer objects we operate on - internal
EndpointQualifier - I believe this class is added to make protocol code generator happy. It is only useful for advanced network configuration(which Java has, but I believe other clients don't), so it should be good to make it private. - internal
MemberInfo - AddressMap this is also related to advanced network config, I believe this one can be made private too - internal
BytesExtensions#ReadUtf8Char(Byte[], ref Int32) (and write too) - The documentation says that it operates …
=> Refactoring following reviews (3)

src/Hazelcast.Net/NetStandard/StreamExtensions.cs, src/Hazelcast.Net/Networking/SocketConnectionBase.cs
There was a nasty memory leak in stream `ReadAsync` that has been exposed by soak tests.
Fixed.
=> Bugfix: memory leak in stream ReadAsync

doc/dev/doc/gettingStarted.md, doc/dev/doc/obtaining.md, hz.ps1, src/Hazelcast.Net.Testing/Hazelcast.Net.Testing.csproj, src/Hazelcast.Net.Tests/Hazelcast.Net.Tests.csproj, src/Hazelcast.Net.Tests/Networking/AddressProviderTests.cs, src/Hazelcast.Net.Tests/Remote/ClientMapTest.cs, src/Hazelcast.Net.Tests/Remote/DnsTests.cs, src/Hazelcast.Net/Core/Attempt`TResult.cs, src/Hazelcast.Net/Networking/CloudDiscovery.cs
A set of minor fixes:
* Cleanup the `hz` script for running tests
* Commit the protocol submodule version, now that latest changes have been merged into the protocol repo
* Fix NUnit versions mismatches that produced warnings when building
* Fix a missing line in `CouldDiscovery` and fix the corresponding tests
* Fix various files to get rid of warnings when building
=> Misc fixes (warnings, dependencies...)

src/Hazelcast.Net.Testing/HazelcastTestBase.cs, src/Hazelcast.Net.Tests/Core/AsyncContextTests.cs, src/Hazelcast.Net.Tests/DotNet/AsyncTests.cs, src/Hazelcast.Net.Tests/Remote/ClientMapTest.cs, src/Hazelcast.Net.Tests/Remote/ClientMultiMapTest.cs, src/Hazelcast.Net/Core/AsyncContext.cs, src/Hazelcast.Net/DistributedObjects/DistributedObjectBase.cs, src/Hazelcast.Net/Transactions/TransactionContext.cs
Fixes: #359 
Following discussions on the internal TDD this refactors the `AsyncContext` class with the following principles:
* code always executes within an implicit async context
* all locks are re-entrant by default, within that async context
* one can execute code in a new, isolated, async context by "using" a new context
For instance:
```csharp
using (AsyncContext.New())
{
await DoSomethingAsync();
}
```
=> Refactor AsyncContext

src/Hazelcast.Net.Tests/Remote/ClientMapTest.cs, src/Hazelcast.Net.Tests/Remote/ClientTxnMapTest.cs, src/Hazelcast.Net.Tests/Remote/ClientTxnTest.cs, src/Hazelcast.Net.Tests/Remote/MapTests.cs
Some adjustments to tests required for 4.2 server compatibility - especially,
* 4.2 throws `TransactionTimeoutException` in case of a transaction timeout and not `TransactionException` anymore
* 4.2 map entry stats have slightly changed
=> Adjustments for 4.2 server compatibility

hz.ps1, src/Hazelcast.Net.Win32/Hazelcast.Net.Win32.csproj, src/Hazelcast.Net.Win32/Security/Win32/AuthIdentity.cs, src/Hazelcast.Net.Win32/Security/Win32/CredentialHandle.cs, src/Hazelcast.Net.Win32/Security/Win32/Enums.cs, src/Hazelcast.Net.Win32/Security/Win32/SspiContext.cs, src/Hazelcast.Net.Win32/Security/Win32/SuppliedCredential.cs
As part of the main build, now build and publish the Hazelcast.Net.Win32 NuGet package.
This package is required for people to use Kerberos with our client, without building the DLL themselves.
=> Build and publish Hazelcast.Net.Win32 NuGet package

hz.ps1
Web requests initiated by the hz script should use the `UseBasicParsing` as per [this documentation page](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest) - the parameter is obsolete for PS 7+, but required for PS 5 in some environments where IE is not available. Otherwise, the build may fail in these environments.
=> Fix hz script with UseBasicParsing

src/Hazelcast.Net.Tests/Clustering/LoadBalancingTests.cs, src/Hazelcast.Net/Clustering/ClusterMembers.cs, src/Hazelcast.Net/Clustering/LoadBalancing/ILoadBalancer.cs, src/Hazelcast.Net/Clustering/LoadBalancing/LoadBalancerBase.cs, src/Hazelcast.Net/Clustering/LoadBalancing/RandomLoadBalancer.cs, src/Hazelcast.Net/Clustering/LoadBalancing/RoundRobinLoadBalancer.cs, src/Hazelcast.Net/Clustering/LoadBalancing/StaticLoadBalancer.cs
After: #448
Misc. cleanup of the load-balancing code. Only internals, no functional changes.
=> Cleanup load-balancing

src/Hazelcast.Net.Tests/Remote/ClientTests.cs, src/Hazelcast.Net/HazelcastClientFactory.cs, src/Hazelcast.Net/HazelcastClientStart.cs
This allows the `HazelcastClientFactory` to return the client before it has started, along with a `Task` representing the start operation.
Fixes #361
=> Add support for starting the client asynchronously

src/Hazelcast.Net.Tests/DotNet/AsyncTests.cs, src/Hazelcast.Net.Tests/Remote/ClientMapTest.cs, src/Hazelcast.Net/Clustering/Heartbeat.cs, src/Hazelcast.Net/Metrics/MetricUnit.cs, src/Hazelcast.Net/Metrics/MetricsCompressor.cs, src/Hazelcast.Net/Metrics/MetricsPublisher.cs, src/Hazelcast.Net/Networking/SocketConnectionBase.cs, src/Hazelcast.Net/Partitioning/Strategies/StringPartitioningStrategy.cs
Just a small PR to get rid of all FIXMEs in the code and of all other warnings.
=> Get rid of FIXMEs in code and all warnings

hz.ps1
I faced a problem when a java class path contains white spaces in it, controller and server doesn't work. Quoted the all usages of `$script:options.classpath`, and tested with run-server and test commands.
=> Pws white space fix

.github/workflows/jira-label.yml, Hazelcast.Net.sln
Proposing changes for the Jira workflow:
- Rename the label workflow file to `jira-label.yml`
- Get it to trigger on the `Jira` label too, so we can rename the label
- Does not trigger if the issue title already contains `[API-`
That last one condition is added so that we can add the `Jira` label to an issue or PR that we have already manually linked to Jira, and prevent the workflow from triggering. Or, should we remove the label by accident, we can add it back without the workflow triggering. Yes, happened to me, and I ended up with duplicates in Jira.
Note: if/when the PR is merged, the `to-jira` label can (should) be renamed to `Jira`.
=> Adjustments to Jira workflow

src/Hazelcast.Net.Tests/Clustering/RetryStrategyTests.cs, src/Hazelcast.Net/Clustering/RetryStrategy.cs
As exposed by the Cloud tests during release validation, we have a bug in our RetryStrategy where, if the timeout is set to -1 (i.e. infinite timeout), the delay is consistently zero. This fixes the issue + adds tests.
=> Fix RetryStrategy delay

src/Hazelcast.Net.Tests/Clustering/ConnectMembersTests.cs, src/Hazelcast.Net/Clustering/ClusterMembers.cs, src/Hazelcast.Net/Clustering/MemberConnectionQueue.cs, src/Hazelcast.Net/Clustering/MemberConnectionRequest.cs, src/Hazelcast.Net/Core/AsyncQueue.cs
During wrapping up of `release/5.1.0` we realized that the Java code in `TcpClientConnectionManager` is testing all clients once every second (see line 340) which means that a member that fails to connect will be retried 1s later. In our own code, the `MemberConnectionQueue` requeues failed members immediately, meaning that if there is only 1 member and it's constantly failing, we'll retry as fast as we can.
This PR adds a special case for failed requests which are "added again". Basically we fire a background task that adds the request back after 1s. That task is cancelled if the whole queue is completed (when the client shuts down) so it's not blocking things. And, the request is put in a special set so that it is canceled if needed.
=> Delay failed members connections

src/Hazelcast.Net.Testing/TestUtils.cs, src/Hazelcast.Net.Tests/Serialization/DataInputOutputTest.cs, src/Hazelcast.Net.Tests/Serialization/Objects/KitchenSinkDataSerializable.cs, src/Hazelcast.Net.Tests/Serialization/Objects/KitchenSinkPortable.cs, src/Hazelcast.Net/Serialization/ObjectDataInput.api.cs
**Problem:**
`ReadStringArray` was only reading if the total size of array is larger than 16 bytes which was not work for the strings that are shorter than 16 bytes. 
**Solution:**
Size of a UTF8 character could be 1 to 4 bytes, so I changed the size checking to 1 byte. Also, added various test cases. There are test cases that covers 0,1,2,3,4 and 10 length of arrays. Also, string arrays will be produced with different size of strings.
```
String arrays will be like;
["x"]
["x", "xx"]
["x", "xx", "xxx"]
["x", "xx", "xxx", "xxxx"]
["x", "xx", "xxx", "xxxx", ..., "xx....xxx"]
```
=> `ReadStringArray` Fixed and Tests Case Enlarged [API-1413]

src/Hazelcast.Net.Testing/TestUtils.cs, src/Hazelcast.Net.Tests/Serialization/DataInputOutputTest.cs, src/Hazelcast.Net.Tests/Serialization/Objects/KitchenSinkDataSerializable.cs, src/Hazelcast.Net.Tests/Serialization/Objects/KitchenSinkPortable.cs, src/Hazelcast.Net/Serialization/ObjectDataInput.api.cs
Backport of:
* Read size fixed
* Review changes.
(cherry picked from commit 8c27ae15a973ae86dee0500625b822caaae4f6a2)
(cherry picked from commit 6e58e76c648bdc72e222a62ff46f3489b4131754)
=> Backport of `ReadStringArray` Fixed and Tests Case Enlarged [API-1413] (#649) to `v5.1.z`

src/Hazelcast.Net.Tests/Clustering/FailoverTests.cs
A case is added to test that client is try to reconnect before doing a failover.
=> Test Added for Retry Before Failover

src/Hazelcast.Net.Examples/SoakTests/Soak1.cs, src/Hazelcast.Net.Testing/MultiMembersRemoteTestBase.cs, src/Hazelcast.Net.Tests/Clustering/ConnectMembersTests.cs, src/Hazelcast.Net.Tests/Clustering/MemberConnectionTests.cs, src/Hazelcast.Net.Tests/Clustering/RetryStrategyTests.cs, src/Hazelcast.Net.Tests/Remote/UnisocketTests.cs, src/Hazelcast.Net/Clustering/ClusterConnections.cs, src/Hazelcast.Net/Clustering/ClusterMembers.cs, src/Hazelcast.Net/Clustering/MemberConnection.cs, src/Hazelcast.Net/Clustering/MemberConnectionQueue.cs, src/Hazelcast.Net/Clustering/MemberConnectionRequest.cs, src/Hazelcast.Net/Clustering/RetryStrategy.cs, src/Hazelcast.Net/Core/AsyncQueue.cs
All fixes that are known for `5.0.3` are backported.
- Unisocket (non-smart-routing) mode is known to be unreliable (https://github.com/hazelcast/hazelcast-csharp-client/issues/595)
- Retry Strategy Period Calculation(https://github.com/hazelcast/hazelcast-csharp-client/issues/657)
- Delay on Member Reconnection (https://github.com/hazelcast/hazelcast-csharp-client/issues/658)
- Member list logging is too verbose (https://github.com/hazelcast/hazelcast-csharp-client/issues/596)
=> Backport Fixes of Known Issues on 5.0.3 [API-1449]

src/Hazelcast.Net.Testing/Networking/SocketListener.cs, src/Hazelcast.Net.Testing/Networking/TestEndPointPort.cs, src/Hazelcast.Net.Tests/Clustering/MemberConnectionTests.cs, src/Hazelcast.Net.Tests/Core/SocketExtensionsTests.cs, src/Hazelcast.Net.Tests/Messaging/ClientMessageConnectionTests.cs
Fix (hopefully) more unstable tests.
Some connection tests that use a custom port (eg 11000) keep failing and I *think* it's due to using the same port in two tests. We did have something in place to randomize the port, but not accross *all* tests. I have put in place a "ports source" that is going to supply ports eg 11000, 11001, 11002 for these tests (all of them) in order to see if it helps.
It's important because for compact, where we have about 18 PRs, 1/2 of them keep failing the build because of stupid tests.
=> Fix more tests [API-1470]

src/Hazelcast.Net.Tests/Sql/SqlQueryResultTests.cs
Fixing a test that was unstable. It was doing:
```
using var cancellationSource = new CancellationTokenSource(50);
await result.Take(5).ToListAsync(cancellationSource.Token);
```
And expecting an exception, but depending on timing, the `CancellationTokenSource` could cancel after the `ToListAsync` has completed. It's a bad idea to depend on timing. Replacing with:
```
using var cancellationSource = new CancellationTokenSource();
var count = 0;
await result.Take(5).Select(x =>
{
if (count++ == 2) cancellationSource.Cancel();
return x;
}).ToListAsync(cancellationSource.Token);
```
So essentially cancelling the `CancellationTokenSource` after 3 items have been returned, so we *know* it's going to be cancelled in a controlled way and before `ToListAsync` completes.
=> Fix unstable tests

src/Hazelcast.Net/Polyfills/IsExternalInit.cs
In preparation for compact serialization, we upgrade our C# language version to version 9 (current latest version being 10). This will allow us to simplify how we handle generic constraints in some situations. This is purely a client code level thing and has no impact on the resulting code that we ship or on people using our client.
=> [compact 5] Upgrade to C# 9 [API-971]

src/Hazelcast.Net/Serialization/ObjectDataOutput.cs
Fixing a critical but unnoticed issue in `ObjectDataOutput`.
=> [compact-6] Fix critical issue in ObjectDataOutput [API-971]

src/Hazelcast.Net.Tests/Properties/AssemblyInfo.cs
A minor adjustment to our tests to enable mocking our test interfaces - does not impact shipped code.
=> [compact 8] Support mocking of Hazelcast.Net.Tests assembly's own interfaces [API-971]

src/Hazelcast.Net/Core/TypeExtensions.cs, src/Hazelcast.Net/Serialization/IReadObjectsFromObjectDataInput.cs, src/Hazelcast.Net/Serialization/IWriteObjectsToObjectDataOutput.cs, src/Hazelcast.Net/Serialization/ObjectDataInput.api.cs, src/Hazelcast.Net/Serialization/ObjectDataInput.cs, src/Hazelcast.Net/Serialization/ObjectDataOutput.api.cs, src/Hazelcast.Net/Serialization/ObjectDataOutput.cs, src/Hazelcast.Net/Serialization/SerializationService.ReadWrite.cs, src/Hazelcast.Net/Serialization/SerializationService.cs
Abstract the capability of reading & writing objects to `ObjectDataOutput` and from `ObjectDataInput` in an interface that can easily be mocked in tests.
=> [compact 9] Serialization - Introduce IRead/WriteObjectsFrom/ToObjectDataInput/Output [API-971]

src/Hazelcast.Net.Tests/Networking/AddressProviderTests.cs, src/Hazelcast.Net.Tests/Networking/NetworkAddressTests.cs, src/Hazelcast.Net/Clustering/ClusterConnections.cs, src/Hazelcast.Net/Networking/AddressProvider.cs, src/Hazelcast.Net/Networking/CloudAddressProviderSource.cs, src/Hazelcast.Net/Networking/ConfigurationAddressProviderSource.cs, src/Hazelcast.Net/Networking/IAddressProviderSource.cs
closing #677 
The PR restructure how a source provides addresses to the `AddressProvider`, so that the source can provide *primary* and *secondary* addresses just like Java does. A new `ExpandedPortsAreSecondaryAddresses` test has been added to `AddressProviderTests` to validate that expanded ports (5702, 5703...) are returned as secondary while 5701 is primary. Next, `ClusterConnection` has been fixed to shuffle primary and secondary addresses, without mixing them, thus testing all 5701 ports before expanded ports.
=> Refactor port expansion [API-1486]

src/Hazelcast.Net.Examples/Serialization/CompactSerializationFullConfigExample.cs, src/Hazelcast.Net.Examples/Serialization/CompactSerializationZeroConfigExample.cs
Provides the same code examples as Java does [here](https://github.com/hazelcast/hazelcast-code-samples/tree/master/serialization/compact/src/main/java). Simple but considered enough.
Remember: to run examples, start a server with `./hz.ps1 run-server` and then in another console, `./hz.ps1 run-example Serialization.CompactSerializationZeroConfigExample` will run the example.
=> Provide compact examples (same as Java) [API-978]

src/Hazelcast.Net.Benchmarks/CompareAutoBatcher.cs, src/Hazelcast.Net.Tests/Clustering/ClientConnectionsTests.cs, src/Hazelcast.Net.Tests/Clustering/InvocationTests.cs, src/Hazelcast.Net.Tests/Clustering/MemberConnectionTests.cs, src/Hazelcast.Net.Tests/FlakeId/AutoBatcherTests.cs, src/Hazelcast.Net.Tests/Messaging/ClientMessageConnectionTests.cs, src/Hazelcast.Net.Tests/NearCache/NearCacheTest.cs, src/Hazelcast.Net/Clustering/Invocation.cs, src/Hazelcast.Net/Clustering/MemberConnection.cs, src/Hazelcast.Net/Core/Clock.cs, src/Hazelcast.Net/DistributedObjects/Impl/AutoBatcher.cs, src/Hazelcast.Net/DistributedObjects/Impl/AutoBatcherBase.cs, src/Hazelcast.Net/Messaging/ClientMessageConnection.cs, src/Hazelcast.Net/NearCaching/NearCacheBase.cs
This PR adds some tests and fixes a few things, in order to ensure a more stable tests coverage. Looking at [this Codecov report](https://app.codecov.io/gh/hazelcast/hazelcast-csharp-client/pull/731) for instance, it was clear at one point that the PR was reducing coverage because it did not run through some code paths, mostly due to timing issues. This is annoying. With these tests, we should *always* run through these code paths, and things should be better.
=> More stable tests coverage

src/Hazelcast.Net.Linq.Async/Visitors/QueryBinder.cs, src/Hazelcast.Net.Tests/Linq/QueryBinderTests.cs, src/Hazelcast.Net.Tests/Linq/QueryBuildingTests.cs
=> Fix naming confusion on LINQ.

hz.ps1, src/Hazelcast.Net.Tests/Protocol/HoldersTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/SchemasLocalTests.cs, src/Hazelcast.Net/Models/BTreeIndexOptions.cs, src/Hazelcast.Net/Models/Capacity.cs, src/Hazelcast.Net/Models/IndexOptions.cs, src/Hazelcast.Net/Models/MemoryTierOptions.cs, src/Hazelcast.Net/Models/MemoryUnit.cs, src/Hazelcast.Net/Protocol/BuiltInCodecs/CustomTypeFactory.cs, src/Hazelcast.Net/Protocol/BuiltInCodecs/SetUUIDCodec.cs, src/Hazelcast.Net/Protocol/Codecs/ClientFetchSchemaCodec.cs, src/Hazelcast.Net/Protocol/Codecs/ClientSendAllSchemasCodec.cs, src/Hazelcast.Net/Protocol/Codecs/ClientSendSchemaCodec.cs, src/Hazelcast.Net/Protocol/Codecs/SqlExecuteCodec.cs, src/Hazelcast.Net/Protocol/CustomCodecs/BTreeIndexConfigCodec.cs, src/Hazelcast.Net/Protocol/CustomCodecs/CapacityCodec.cs, src/Hazelcast.Net/Protocol/CustomCodecs/FieldDescriptorCodec.cs, src/Hazelcast.Net/Protocol/CustomCodecs/MemoryTierConfigCodec.cs, src/Hazelcast.Net/Protocol/CustomCodecs/PagingPredicateHolderCodec.cs, src/Hazelcast.Net/Protocol/CustomCodecs/SchemaCodec.cs, src/Hazelcast.Net/Protocol/Models/PagingPredicateHolder.cs
In order to work on an issue with `Guid` (Java `UUID`) (de)serialization in codecs, we need to be able to re-generate the C# code for all codecs. Alas, the `hazelcast-client-protocol` repo has gotten out-of-sync: some of our changes were never merged there, and some codec definitions were extended.
Also, codecs were not necessarily generated as true UTF8+BOM files which can cause confusion during reviews (suddenly all codec files change because of encoding) so we need to stabilize this.
**This PR can only be merged after [hazelcast-client-protocol/442](https://github.com/hazelcast/hazelcast-client-protocol/pull/442) has been reviewed and merged. And then, the `protocol` submodule in this PR needs to be updated to the correct commit in the `hazelcast-client-protocol` repository.**
Then, …
=> Update codecs [API-1706]

src/Hazelcast.Net.Tests/Serialization/Compact/SchemasLocalTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/SchemasRemoteTests.cs, src/Hazelcast.Net/Clustering/Cluster.cs, src/Hazelcast.Net/Clustering/ClusterEvents.cs, src/Hazelcast.Net/HazelcastClient.cs, src/Hazelcast.Net/Messaging/IClusterMessaging.cs, src/Hazelcast.Net/Serialization/Compact/Schemas.cs
This PR groups all events wiring in one single place in `HazelcastClient`, thus giving a clear view of what happens, and when.
Also, it re-orders some events to ensure that, for instance, Compact Serialization schemas are sent to a new cluster *before* the client is considered connected and can issue user-level invocations. This is documented in the source code.
=> Rewire Events [API-1824]

src/Hazelcast.Net/Clustering/ClusterEvents.cs, src/Hazelcast.Net/Core/ConnectionRetryOptions.cs
Fix null connection exception during dispose at cluster view subscription. `WaitForConnection ` returns null if cancelation is requested. During process, `SubscribeToClusterViewsAsync` takes null connection as an argument and fails. That causes problem while disposing the client, and so on tests.
Edit: Also, fixed the default value of multiplier in `ConnectionRetryOptions`.
=> Fix null connection exception during dispose [API-1821]

src/Hazelcast.Net/Clustering/ClusterConnections.cs, src/Hazelcast.Net/Clustering/RetryStrategy.cs
Retry strategy was logging in debug level. It's hard to see if retry strategy is working in normal circumstances. So, aligned the log level with Java client and made it more visible.
=> Make Retry Strategy Logs More Visible [API-1832]

src/Hazelcast.Net.Tests/Networking/NetworkingTests.cs, src/Hazelcast.Net.Tests/Networking/RegressionWithRealNetworkTest.cs, src/Hazelcast.Net.Tests/Remote/ClientTests.cs, src/Hazelcast.Net/Networking/NetworkingOptions.cs
Corrected the default mode, and fixed the related tests. Documentation matches with the behavior now.
=> Default Reconnect Mode Set to Sync [API-1857]

src/Hazelcast.Net.Testing/Accessors/MemberConnectionAccessor.cs, src/Hazelcast.Net.Testing/RemoteControllerClientExtensions.cs, src/Hazelcast.Net.Tests/Clustering/ConnectMembersTests.cs, src/Hazelcast.Net.Tests/Clustering/MemberConnectionTests.cs, src/Hazelcast.Net.Tests/Clustering/SubscriptionCollectTests.cs, src/Hazelcast.Net.Tests/Remote/ClientTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/CompactQaTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/CompactSerializationSerializerTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/CompactSerializerTests.cs, src/Hazelcast.Net/Clustering/ClusterConnections.cs, src/Hazelcast.Net/Clustering/ClusterEvents.cs, src/Hazelcast.Net/Clustering/ClusterMembers.cs, src/Hazelcast.Net/Clustering/ClusterMessaging.cs, src/Hazelcast.Net/Clustering/DistributedEventScheduler.cs, src/Hazelcast.Net/Clustering/MemberConnection.cs, src/Hazelcast.Net/Clustering/MemberConnectionQueue.cs, src/Hazelcast.Net/Core/DisposeAction.cs, src/Hazelcast.Net/Core/DisposeAsyncAction.cs, src/Hazelcast.Net/Core/HConsole.cs, src/Hazelcast.Net/Core/HConsoleOptions.cs, src/Hazelcast.Net/HazelcastClientFactory.cs, src/Hazelcast.Net/Serialization/Compact/CompactSerializationSerializer.cs, src/Hazelcast.Net/Serialization/Compact/Schemas.cs
NOTE: this is PR #782 but for some reason GitHub does not pick the latest changes that were force-pushed after a rebase. It usually always work, no idea what is happening here. This PR is *identical* to the other one except it's rebased on top of `master`.
This PR addresses issues raised during QA review of Compact Serialization. This issues are highlighted by the newly introduced `CompactQaTests` class. The two issues were:
* As per `ClusterRestart` test, the client would hang when trying to reconnect to a cluster. This was caused by `Schemas.PublishSchemasAsync` where we need to use `SendToMemberAsync` not `SendAsync` when reconnecting, but we forgot to update one of the two cases of the `switch` statement.
* As per `ReadSchemaAfterWrite_withObjectValueType`, a map of `<int, object>` …
=> [API-1824] Fix Compact Serialization as per QA

src/Hazelcast.Net/Clustering/Cluster.cs, src/Hazelcast.Net/Clustering/Heartbeat.cs, src/Hazelcast.Net/Clustering/MemberConnection.cs, src/Hazelcast.Net/Messaging/ClientMessageConnection.cs, src/Hazelcast.Net/Messaging/ConnectionLifeState.cs, src/Hazelcast.Net/Messaging/ConnectionLifeStateExtensions.cs
This is the final preparation PR for TPC. This one refactors heartbeat (because we're going to have to heartbeat TPC connections too).
The idea here is that heartbeat now asks the `MemberConnection` to report all the `ClientMessageConnection` it has (currently still only 1) and each `ClientMessageConnection` is able to report its `ConnectionLifeState` which is either `Dead` (timed out), `Cold` (not used in a long time) or `Warm` (used recently). And it's up to heartbeat to sort them out and terminates the `Dead` ones and ping the `Cold` ones. 
Also `MemberConnection` now has an additional message to send a message (here, the ping request) to one specific underlying `ClientMessageConnection`.
When we implement TPC, the `MemberConnection` will simply have to return the TPC connection too, …
=> Prepare for TPC (3) [API-1850]

src/Hazelcast.Net.Testing/AssertEx.cs, src/Hazelcast.Net.Tests/Clustering/FailoverTests.cs, src/Hazelcast.Net.Tests/Clustering/FailoverTests2.cs, src/Hazelcast.Net/Clustering/ClusterConnections.cs, src/Hazelcast.Net/Clustering/ClusterEvents.cs, src/Hazelcast.Net/Clustering/ClusterState.cs, src/Hazelcast.Net/Clustering/Heartbeat.cs, src/Hazelcast.Net/Clustering/MemberConnection.cs, src/Hazelcast.Net/Clustering/RetryStrategy.cs, src/Hazelcast.Net/Core/ConnectionRetryOptions.cs, src/Hazelcast.Net/Core/IRetryStrategy.cs
This PR fixes #863 and introduces the following changes:
- Add the `FailoverTests2` test class that reproduces the tests from `FailoverTests` but works with mock clusters instead of actual clusters, so that we can tweak the behavior of the clusters, and reproduce a cluster not sending the members view event within a reasonable time
- Modify `HeartBeat` to ensure that the cancellation tokens are properly propagated down to the ping messages, which will then abort correctly in case the cluster goes down
- Modify `RetryStrategy` to expose a cancellation token corresponding to the cluster connection timeout, that can be used even before we have to retry, to detect that the timeout has been reached (for instance, while waiting for the member views event)
- Modify `ClusterConnections` to ensure …
=> Fix: Client shuts down on failover [API-2176]

.github/actions/install/action.yml
The `setup-java` [documentation highlights that AdoptOpenJDK no longer receives security updates](https://github.com/actions/setup-java#:~:text=NOTE%3A%20AdoptOpenJDK%20got%20moved%20to%20Eclipse%20Temurin), and instead the Eclipse Temurin JDK should be used.
Fixes [HZ-4195](https://hazelcast.atlassian.net/browse/HZ-4195)
[HZ-4195]: https://hazelcast.atlassian.net/browse/HZ-4195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Migrate GitHub actions from AdoptOpenJDK to Eclipse Temurin [HZ-4195]

src/Hazelcast.Net.Testing/Hazelcast.Net.Testing.csproj, src/Hazelcast.Net.Testing/Linq/LinqTestingExtension.cs, src/Hazelcast.Net.Tests/Caching/HazelcastCacheTests.cs, src/Hazelcast.Net.Tests/Clustering/FailoverTests.cs, src/Hazelcast.Net.Tests/Clustering/MemberConnectionTests.cs, src/Hazelcast.Net.Tests/Core/SingletonLoggerFactoryServiceFactoryTests.cs, src/Hazelcast.Net.Tests/Events/EventHandlers.cs, src/Hazelcast.Net.Tests/Hazelcast.Net.Tests.csproj, src/Hazelcast.Net.Tests/Linq/HzExpressionVisitorTests.cs, src/Hazelcast.Net.Tests/Linq/QueryFormatterTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/CompactOptionsTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/CompactReaderTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/CompactSerializationSerializerTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/CompactSerializerTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/CompactWriterTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/GenericRecordTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/ReaderWriterTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/ReflectionSerializerTests.cs, src/Hazelcast.Net.Tests/Serialization/Compact/SchemasRemoteTests.cs, src/Hazelcast.Net.Tests/Serialization/SerializationServiceBuilderTest.cs
This PR replaces the Moq library that we used for mocking in tests, with the NSubstitute library. As documented in issue #850 Moq has a problematic attitude with regards to privacy (see [moq/issues/1372](https://github.com/moq/moq/issues/1372)) and we'd rather avoid using it.
=> Replaces Moq with NSubsitute [API-2119]

.github/actions/install/action.yml, hz.ps1, src/Hazelcast.Net.Tests/Support/Issue868.cs, src/Hazelcast.Net/DistributedObjects/Impl/HMap.Getting.cs, src/Hazelcast.Net/Protocol/Models/AnchorDataListHolder.cs, src/Hazelcast.Net/Query/PagingPredicate.cs, src/Hazelcast.Net/Serialization/Compact/Schemas.cs
This PR fixes issue #868 by ensuring that `PagingPredicate` anchors can be deserialized, including if they are compact-serialized and a schema needs to be fetched.
=> Fix issue 868

src/Hazelcast.Net.Tests/Clustering/FailoverTests.cs, src/Hazelcast.Net/Clustering/ClusterConnections.cs, src/Hazelcast.Net/Clustering/ClusterMembers.cs
=> Clear Members Before Failover Over to New Cluster [API-2217]

.github/workflows/build-and-test.yml, hz.ps1
`ensure-server-files` downloads `hazelcast-default.xml` from the `hazelcast` repo.
[This failed](https://github.com/hazelcast/client-compatibility-suites/actions/runs/9882576769/job/27296050800), now that we have EE specific patches, where corresponding tags do not exist in `hazelcast-mono`:
> Downloading hazelcast-default.xml -> hazelcast-5.4.1-SNAPSHOT.xml...
> Failed to download hazelcast-default.xml (404) from tag v5.4.1
Updated script to:
- Use `hazelcast-mono`, not `hazelcast` as source
- Centralise downloading into a single function
=> Make `ensure-server-files` use `hazelcast-mono`

hz.ps1
The script queries if the branch name starts with `release`, using the `git symbolic-ref` command.
[While testing the `client-compatibility-suites`](https://github.com/hazelcast/client-compatibility-suites/actions/runs/9908837208/job/27376177353), it was noticed that for detached branches, [this command throws an error (`fatal: ref HEAD is not a symbolic ref`) and stops the script](https://stackoverflow.com/a/45028375).
=> Make `git` branch resolution in script more more tolerant

build/build.proj, doc/dev/doc/network.md, doc/versions.md, hz.ps1, src/Hazelcast.Net.Caching/Hazelcast.Net.Caching.csproj, src/Hazelcast.Net.DependencyInjection/Hazelcast.Net.DependencyInjection.csproj, src/Hazelcast.Net.Examples/Hazelcast.Net.Examples.csproj, src/Hazelcast.Net.Linq.Async/Hazelcast.Net.Linq.Async.csproj, src/Hazelcast.Net.Tests/Hazelcast.Net.Tests.csproj, src/Hazelcast.Net.Win32/Hazelcast.Net.Win32.csproj, src/Hazelcast.Net/Hazelcast.Net.csproj
.Net 7 support ended at May 14, 2024. We also drop support in Hazelcast .Net client.
=> Drop Net7 Support [API-2249]

src/Hazelcast.Net.Tests/CP/AtomicLongTests.cs, src/Hazelcast.Net.Tests/CP/AtomicReferenceTests.cs, src/Hazelcast.Net.Tests/CP/CPMapTests.cs, src/Hazelcast.Net.Tests/CP/CPRoutingTests.cs, src/Hazelcast.Net.Tests/CP/CountDownLatchTests.cs, src/Hazelcast.Net.Tests/CP/FencedLockTests.cs, src/Hazelcast.Net.Tests/CP/SemaphoreTests.cs, src/Hazelcast.Net.Tests/Resources/Cluster/cp.xml, src/Hazelcast.Net/CP/CPSubsystem.cs
The PR fixes wrong usage of CP groups. Before the introduced fix, the client was sending the CP group creation requests in wrong format. This was resulting that all CP objects created in `default` CP group. Now, it's fixed.
=> Fix CP Group Name in CP Objects [API-2252]

src/Hazelcast.Net.Tests/Clustering/ConnectMembersTests.cs, src/Hazelcast.Net.Tests/Clustering/MemberConnectionQueueTests.cs, src/Hazelcast.Net.Tests/Clustering/MemberConnectionTests.cs, src/Hazelcast.Net.Tests/Clustering/MemberPartitionGroupServerTests.cs, src/Hazelcast.Net.Tests/Clustering/MemberPartitionGroupTests.cs, src/Hazelcast.Net/Clustering/ClusterConnections.cs, src/Hazelcast.Net/Clustering/ClusterMembers.cs, src/Hazelcast.Net/Clustering/MemberConnectionQueue.cs, src/Hazelcast.Net/Clustering/MemberPartitionGroup.cs, src/Hazelcast.Net/Models/MemberGroups.cs
In `MultiMember` routing mode, the `GetMembers` was returining only connected members. It must return the last known all members in the cluster.
=> Fix GetMembers for `MultiMember` routing mode [API-2255]

src/Hazelcast.Net.Testing/NoOpSubsetMembers.cs, src/Hazelcast.Net.Tests/Clustering/MemberPartitionGroupServerTests.cs, src/Hazelcast.Net.Tests/Clustering/MemberPartitionGroupServerTests2.cs, src/Hazelcast.Net.Tests/Clustering/MemberPartitionGroupServerTestsNightly.cs, src/Hazelcast.Net.Tests/Clustering/MemberPartitionGroupTests.cs, src/Hazelcast.Net/Clustering/Authenticator.cs, src/Hazelcast.Net/Clustering/ClusterEvents.cs, src/Hazelcast.Net/Clustering/ClusterMembers.cs, src/Hazelcast.Net/Clustering/ISubsetClusterMembers.cs, src/Hazelcast.Net/Clustering/MemberPartitionGroup.cs, src/Hazelcast.Net/Models/MemberGroups.cs, src/Hazelcast.Net/Polyfills/CollectionExtensions.cs
The partition group for `MultiMember` routing was changing on `ClusterView` updates based on version comparison. However, later updates should be done by considering first authenticated member id in the partition group. This PR fixes unwanted parition group changing on later `ClusterView` events.
=> Fix Partition Group Selection on `ClusterView` Event [API-2259]

.github/workflows/build-and-test.yml
Upload action ha newer version. See details for #916
=> Upgrade Upload Action

hz.ps1
The issue is `dotcover` tools fails due to undetected globalization
while running the tests.
```
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
``` 
This PR only touches the `hz.ps1` building scripts. It needs to be
forced to merge since tests on Ubuntu will fail.
=> Fix Missing Globalization option for Ubuntu based ENV on Github Builds on Powershell script

.github/actions/install/action.yml, .github/workflows/build-and-test.yml, build/build.proj, hz.ps1, src/Hazelcast.Net.Tests/Hazelcast.Net.Tests.csproj
Upgraded the `dotcover` and fixed missing globalization dependencies on .Net SDK installation.
=> Upgrade the `dotcover` & Separate with .Net framework and Core Dependencies

src/Hazelcast.Net.Tests/Remote/UnisocketTests.cs, src/Hazelcast.Net/Networking/RoutingModes.cs
Introduced a fix to sync enum values with Java implementation. Hence, connection mode the reporting to the cluster is corrected.
=> Fix `RoutingModes` Enum Values [API-2266]

.github/workflows/build-pr.yml
We restrict actions' execution to members of the `hazelcast` organisation using `hazelcast/hazelcast-tpm/membership`, passing in the user derviced from `github.event.pull_request.head.repo.owner.login`.
This is the owner of the repository, _not_ the user itself.
In the case of a non-fork PR - i.e. one in the `hazelcast` original repo - the `owner` will be `hazelcast` (which _isn't_ a GitHub user, and _isn't_ a member of the `hazelcast` organisation) and will fail.
This nuance prevented https://github.com/hazelcast/hazelcast-python-client/pull/720 from being merged.
Instead we should query `github.actor` as [already used in the C++ client](https://github.com/hazelcast/hazelcast-cpp-client/blame/b63e40748aa8e06f790510d86e1eae87cc36925a/.github/workflows/build-pr.yml#L50).
=> Improve GitHub Actions `hazelcast` membership check

src/Hazelcast.Net.Tests/Remote/UnisocketTests.cs, src/Hazelcast.Net/Networking/RoutingModes.cs
Introduced a fix to sync enum values with Java implementation. Hence, connection mode the reporting to the cluster is corrected.
=> Backport of Fix `RoutingModes` Enum Values [API-2266] [HZG-224] (#934)

src/Hazelcast.Net.Tests/Core/ClientVersionTests.cs, src/Hazelcast.Net.Tests/Remote/TpcLocalTests.cs, src/Hazelcast.Net/Clustering/Authenticator.cs, src/Hazelcast.Net/Clustering/ClusterConnections.cs, src/Hazelcast.Net/Core/ClientVersion.cs, src/Hazelcast.Net/Metrics/ClientMetricSource.cs
Backport of https://github.com/hazelcast/hazelcast-csharp-client/pull/933 to `5.5.z`
=> Backport of Fix Missing Patch Version on Client Version Reporting [API-2245][HZG-327]

hz.ps1
The check should start from including Hazelcast `5.4.0`.
=> Fix Hazelcast Patch Releases JAR Downloads

.github/workflows/build-release.yml
The `ubuntu-latest` doesn't contain .NET6 runtime anymore. I've encountered while [releasing ](https://github.com/hazelcast/hazelcast-csharp-client/actions/runs/15856493278/job/44707500159)the `5.5.1`. Included the install action on release building flow.
=> Install Environment on Build Release Action

.github/actions/install/action.yml, hz.ps1
.Net6 is out of support and removed from `windows-latest`. Added a manual installation step. Also, upgraded target server version.
=> Fix missing .Net6 on windows-latest

hz.ps1
In https://github.com/hazelcast/hazelcast-remote-controller/pull/75, `hazelcast-remote-controller` is deployed to a different repository to address build issues. Update the paths to suit.
Also updated Maven central URL as per https://github.com/hazelcast/hazelcast-mono/pull/4897
Fixes: [DI-639](https://hazelcast.atlassian.net/browse/DI-639)
[DI-639]: https://hazelcast.atlassian.net/browse/DI-639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Relocate `hazelcast-remote-controller` [DI-639]
