hazelcast/hazelcast-csharp-client

- Hazelcast.Net/Hazelcast.IO.Serialization/HeapData.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/SerializationService.cs
- Hazelcast.Test/Hazelcast.Client.Test.Serialization/StringSerializationTest.cs
- build.bat
See https://github.com/hazelcast/hazelcast/pull/6577
> Changes to HeapData layout to match the changes in Java client

- Hazelcast.Net/Hazelcast.Client.Connection/ClientConnection.cs
- Hazelcast.Net/Hazelcast.Client.Connection/ClientConnectionManager.cs
- Hazelcast.Net/Hazelcast.Client.Proxy/ClientMapProxy.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientExecutionService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientInvocationService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientPartitionService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/IClientExecutionService.cs
- Hazelcast.Net/Hazelcast.Util/StripedTaskScheduler.cs
…and give name to all the threads being used.
> make sure ExecutionService is used instead of Task.Factory directly

- Hazelcast.Net/Hazelcast.Client.Protocol.Codec/MapGetAllCodec.cs
- Hazelcast.Net/Hazelcast.Client.Proxy/ClientMapProxy.cs
C# client implementation of hazelcast/hazelcast#6555, fixes issue #19
> Update IMap.GetAll to send a separate request for each partition

- Hazelcast.Examples/Hazelcast.Examples.csproj
- Hazelcast.Examples/Map/MapIdentifiedDataSerializableExample.cs
- Hazelcast.Examples/Models/Employee.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/DataSerializer.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/IIdentifiedDataSerializable.cs
- Hazelcast.Test/Hazelcast.Client.Test.Serialization/DataSerializableType.cs
- Hazelcast.Test/Hazelcast.Client.Test.Serialization/SampleIdentifiedDataSerializable.cs
and add an example for using IdentifiedDataSerializable.
> Add IdentifiedDataSerializable as a convenience class

- Hazelcast.Net/Hazelcast.Client.Protocol.Codec/MapAddNearCacheEntryListenerCodec.cs
- Hazelcast.Net/Hazelcast.Client.Protocol/EventMessageConst.cs
- Hazelcast.Net/Hazelcast.Client/ClientNearCache.cs
- Hazelcast.Net/Hazelcast.Core/EntryEventType.cs
- build.bat
Update NearCache to match changes in RC2
> Update NearCache to match changes in RC2

- Hazelcast.Net/Hazelcast.Core/IPredicate.cs
- Hazelcast.Net/Hazelcast.Core/SqlPredicate.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/ArrayDataSerializableFactory.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/DataSerializer.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/PredicateDataSerializerHook.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/SerializationConstants.cs
- Hazelcast.Net/Hazelcast.Net.csproj
depends on  hazelcast/hazelcast#6883
> Update SqlPredicate to use IIdentifiedDataSerializable

- Hazelcast.Test/Hazelcast.Client.Test/ClientMapTest.cs
> fix ClientMapTest.TestAsyncPutWithTtl to be less time sensitive

- Hazelcast.Net/Hazelcast.Client.Connection/ClientConnection.cs
- Hazelcast.Net/Hazelcast.Client.Connection/ClientConnectionManager.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientClusterService.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientReconnectionTest.cs
When owner connection drops, if another connection was already available
it should be promoted to owner
> [Backport] Promote connections to owner connection if one was available

- Hazelcast.Net/Hazelcast.Client.Connection/ClientConnection.cs
- Hazelcast.Net/Hazelcast.Client.Connection/ClientConnectionManager.cs
- Hazelcast.Net/Hazelcast.Client.Connection/IClientConnectionManager.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientClusterService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientExecutionService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientInvocationService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientMembershipListener.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientPartitionService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/Exception.cs
- Hazelcast.Net/Hazelcast.Client.Spi/IClientExecutionService.cs
- Hazelcast.Net/Hazelcast.IO/Address.cs
- Hazelcast.Net/Hazelcast.Logging/Logger.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientHeartBeatTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientLoggingTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientReconnectionTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/HazelcastTestSupport.cs
- Hazelcast.Test/Hazelcast.Remote/Cluster.cs
- Hazelcast.Test/Hazelcast.Remote/Lang.cs
- Hazelcast.Test/Hazelcast.Remote/RemoteController.cs
- Hazelcast.Test/Hazelcast.Remote/Response.cs
- Hazelcast.Test/Hazelcast.Test.csproj
- Hazelcast.Test/Resources/hazelcast.xml
Also replace heartbeat and partition threads with scheduling service.
> Improve heartbeat handling from client

- Hazelcast.Net/Hazelcast.Client.Connection/ClientConnection.cs
- Hazelcast.Net/Hazelcast.Client.Connection/ClientConnectionManager.cs
- Hazelcast.Net/Hazelcast.Client.Connection/IClientConnectionManager.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientClusterService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientExecutionService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientInvocationService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientMembershipListener.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientPartitionService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/Exception.cs
- Hazelcast.Net/Hazelcast.Client.Spi/IClientExecutionService.cs
- Hazelcast.Net/Hazelcast.IO/Address.cs
- Hazelcast.Net/Hazelcast.Logging/Logger.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientHeartBeatTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientLoggingTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientReconnectionTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/HazelcastTestSupport.cs
- Hazelcast.Test/Hazelcast.Remote/Cluster.cs
- Hazelcast.Test/Hazelcast.Remote/Lang.cs
- Hazelcast.Test/Hazelcast.Remote/RemoteController.cs
- Hazelcast.Test/Hazelcast.Remote/Response.cs
- Hazelcast.Test/Hazelcast.Test.csproj
- Hazelcast.Test/Resources/hazelcast.xml
Also replace heartbeat and partition threads with scheduling service.
> [Backport] Improve heartbeat handling from client

- Hazelcast.Test/Hazelcast.Client.Test/ClientSSLTest.cs
- Hazelcast.Test/Resources/hazelcast-ssl.xml
- build.bat
Test Category is introduced for enterprise
> build fixed to download latest hazelcast and remote-controller

- .gitignore
- Hazelcast.Net/Hazelcast.Client.Connection/ClientConnection.cs
- Hazelcast.Net/Hazelcast.Net.csproj
- start-rc.sh
> connection socket writer thread fixed to catch ThreadInterruptedException

- Hazelcast.Test/Hazelcast.Client.Test/ClientMapTest.cs
- start-rc.sh
> minor EntryProcessor unit test

- Hazelcast.Net/Hazelcast.Client.Connection/ClientConnection.cs
- Hazelcast.Net/Hazelcast.Client.Connection/ClientConnectionManager.cs
- Hazelcast.Net/Hazelcast.Client.Protocol.Util/MessageFlyweight.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientExecutionService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientInvocation.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientInvocationService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientPartitionService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientProxy.cs
- Hazelcast.Net/Hazelcast.Client.Spi/Exception.cs
- Hazelcast.Net/Hazelcast.Client.Spi/SettableFuture.cs
- Hazelcast.Net/Hazelcast.Client/Error.cs
- Hazelcast.Net/Hazelcast.Net.csproj
- Hazelcast.Net/Hazelcast.Util/StackTraceElement.cs
- Hazelcast.Net/Hazelcast.Util/TaskExtension.cs
- Hazelcast.Net/Hazelcast.Util/ThreadUtil.cs
- Hazelcast.Net/Package.nuspec
- Hazelcast.Test/Hazelcast.Client.Test/ClientExecutorServiceTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientRetryTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientShutdownTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/HazelcastTestSupport.cs
- Hazelcast.Test/Hazelcast.Client.Test/SettableFutureTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/TestSupport.cs
- Hazelcast.Test/Hazelcast.Test.csproj
- build.bat
- start-rc.sh
fix unobserved task exception
fix client message byte encode
fix invocation service operation timeouts
> unobserved exception fix

- Hazelcast.Net/Hazelcast.Client.Proxy/ClientMapProxy.cs
- Hazelcast.Net/Hazelcast.Core/Aggregator.cs
- Hazelcast.Net/Hazelcast.Core/Aggregators.cs
- Hazelcast.Net/Hazelcast.Core/IMap.cs
- Hazelcast.Net/Hazelcast.Core/Projection.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/AggregatorDataSerializerHook.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/DataSerializer.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/PredicateDataSerializerHook.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/ProjectionDataSerializerHook.cs
- Hazelcast.Net/Hazelcast.IO.Serialization/SerializationConstants.cs
- Hazelcast.Net/Hazelcast.Net.csproj
- Hazelcast.Net/Hazelcast.Util/ReadOnlyLazyList.cs
- Hazelcast.Test/Hazelcast.Client.Test/AggregatorAndProjectionTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/ReadOnlyLazyListTest.cs
- Hazelcast.Test/Hazelcast.Test.csproj
> Fast aggregation and projection implementation

- Hazelcast.Net/Hazelcast.Util/EnvironmentUtil.cs
- Hazelcast.Test/Hazelcast.Client.Test/EnvironmentUtilTest.cs
- Hazelcast.Test/Hazelcast.Test.csproj
> fix wrong version send to server on auth

- Hazelcast.Net/Hazelcast.IO.Serialization/PortableContext.cs
- Hazelcast.Test/Hazelcast.Client.Test.Serialization/PortableClassVersionTest.cs
> portable class version registration concurrent access fixed

- Hazelcast.Net/Hazelcast.Client.Proxy/ClientMapProxy.cs
- Hazelcast.Net/Hazelcast.Core/PagingPredicate.cs
- Hazelcast.Net/Hazelcast.Util/SortingUtil.cs
- Hazelcast.Test/Hazelcast.Client.Test/PagingPredicateTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/PagingPredicateWithPrimitiveTest.cs
- Hazelcast.Test/Hazelcast.Test.csproj
> paging predicate should handle primitive types

- Hazelcast.Net/Hazelcast.Client.Proxy/ClientMapProxy.cs
- Hazelcast.Net/Hazelcast.Client.Proxy/ClientMultiMapProxy.cs
- Hazelcast.Net/Hazelcast.Core/EntryEvent.cs
- Hazelcast.Net/Hazelcast.Core/EntryEventType.cs
- Hazelcast.Net/Hazelcast.Core/IEntryListener.cs
- Hazelcast.Net/Hazelcast.Core/IMap.cs
- Hazelcast.Net/Hazelcast.Core/MapEvent.cs
- Hazelcast.Net/Hazelcast.Map/EntryListenerAdapter.cs
- Hazelcast.Net/Hazelcast.Net.csproj
- Hazelcast.Net/Hazelcast.Util/ReadOnlyLazySet.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientMapTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/EntryEventTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/ReadOnlyLazySetTest.cs
- Hazelcast.Test/Hazelcast.Test.csproj
> map and multimap listener improvements, DataAwareEventEntry added

- Hazelcast.Examples/Hazelcast.Examples.csproj
- Hazelcast.Examples/Transactions/TransactionBenchmark.cs
- Hazelcast.Net/Hazelcast.Client.Proxy/TransactionContextProxy.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientClusterService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientInvocationService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientListenerService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientNonSmartInvocationService.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientTxnNonSmartTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/NonSmartRoutingTest.cs
- Hazelcast.Test/Hazelcast.Test.csproj
> Transactions should send the invocations to correct member for unisocket clients

- .nuget/packages.config
- Hazelcast.Net/Hazelcast.Client.Spi/ClientExecutionService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientInvocationService.cs
- Hazelcast.Net/Hazelcast.Client.Spi/ClientPartitionService.cs
- Hazelcast.Net/Hazelcast.Core/Member.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientHeartBeatDetailTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientPartitionTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/ClientRetryTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/HazelcastTestSupport.cs
- build.ps1
> fixes owner restart causes client operations hang problem

- .gitignore
- build.ps1
This PR moves the whole coverage outcome to a nested directory
> Coverage outcome moved to a nested directory

- .gitignore
- Hazelcast.Net.sln
- Hazelcast.Net/Hazelcast.Client.Spi/HazelcastCloudDiscovery.cs
- Hazelcast.Test/Hazelcast.Client.Test.Serialization/BufferPoolTest.cs
- Hazelcast.Test/Hazelcast.Client.Test/HazelcastCloudDiscoveryTest.cs
- Hazelcast.Test/test.runsettings
- build.ps1
- build.sh
(backport https://github.com/hazelcast/hazelcast-csharp-client/pull/278)
> Use explicit port on Cloud Discovery for private address 

- Hazelcast.Net/Hazelcast.Client.Spi/ClientClusterService.cs
- README.md
> fix address list shuffle default to true

- src/Hazelcast.Net.Testing/ClusterRemoteTestBase.cs
- src/Hazelcast.Net.Testing/RemoteTestBase.Remoting.cs
- src/Hazelcast.Net.Testing/SingleMemberClientRemoteTestBase.cs
- src/Hazelcast.Net.Tests/Networking/ClientSslTestBase.cs
- src/Hazelcast.Net.Tests/Remote/ClientQueueTest.cs
- src/Hazelcast.Net.Tests/Remote/DictionaryTests.cs
- src/Hazelcast.Net.Tests/Testing/RemoteTests.cs
- src/Hazelcast.Net/Clustering/DistributedEventScheduler.cs
- src/Hazelcast.Net/Core/HConsoleConfiguration.cs
- src/Hazelcast.Net/DistributedObjects/DistributedObjectBase.cs
- src/Hazelcast.Net/DistributedObjects/IHCollection.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HCollectionBase.Events.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HCollectionBase.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HDictionary.Events.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HQueue.Events.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HQueue.Getting.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HQueue.Removing.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HReplicatedDictionary.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HTopic.Events.cs
Port HQueue tests from old codebase.
> Implement HQueue tests

- src/Hazelcast.Net.Examples/DistributedObjects/ListEventsExample.cs
- src/Hazelcast.Net.Examples/DistributedObjects/ListExample.cs
- src/Hazelcast.Net.Examples/DistributedObjects/SetExample.cs
- src/Hazelcast.Net.Examples/WebSite/QueueExample.cs
- src/Hazelcast.Net.Examples/WebSite/SetExample.cs
- src/Hazelcast.Net.Tests/Remote/ClientListTest.cs
- src/Hazelcast.Net.Tests/Remote/ClientQueueTest.cs
- src/Hazelcast.Net.Tests/Remote/ClientSetTest.cs
- src/Hazelcast.Net.Tests/Remote/ClientTopicTest.cs
- src/Hazelcast.Net.Tests/Remote/TransactionTests.cs
- src/Hazelcast.Net/DistributedObjects/IDistributedObject.cs
- src/Hazelcast.Net/DistributedObjects/IHCollection.cs
- src/Hazelcast.Net/DistributedObjects/IHList.cs
- src/Hazelcast.Net/DistributedObjects/IHQueue.cs
- src/Hazelcast.Net/DistributedObjects/IHSet.cs
- src/Hazelcast.Net/DistributedObjects/IHTopic.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HCollectionBase.Events.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HCollectionBase.Getting.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HCollectionBase.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HList.Getting.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HList.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HQueue.Dequeue.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HQueue.Getting.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HSet.Getting.cs
Public API methods renamed based on the TDD
> renaming the IHCollection, IHList, IHSet IHQueue API

- src/Hazelcast.Net/Messaging/ClientMessageConnection.cs
- src/Hazelcast.Net/Messaging/Frame.cs
- src/Hazelcast.Net/Networking/ClientSocketConnection.cs
- src/Hazelcast.Net/Networking/SocketConnectionBase+ReadPipeState.cs
- src/Hazelcast.Net/Networking/SocketConnectionBase.cs
> Improve messaging perfs

- src/Hazelcast.Net.Tests/Networking/SocketConnectionTests.cs
- src/Hazelcast.Net.Tests/Networking/SslLayerTests.cs
- src/Hazelcast.Net/Networking/SslLayer.cs
- src/Hazelcast.Net/Networking/SslOptions.cs
> SSL cleanup

- src/Hazelcast.Net/Core/HConsole.cs
- src/Hazelcast.Net/Data/DistributedObjectKey.cs
- src/Hazelcast.Net/Data/EndpointQualifier.cs
- src/Hazelcast.Net/Data/MemberInfo.cs
- src/Hazelcast.Net/NOTES.txt
> Refactor yet more utilities

- build/dockerfile
Import the jenkins dockerfile so it's managed with the rest of the project
> Add jenkins dockerfile

- src/Hazelcast.Net.Examples/DistributedObjects/MapLockExample.cs
- src/Hazelcast.Net/Core/AsyncContext.cs
- src/Hazelcast.Net/HazelcastClient.cs
- src/Hazelcast.Net/HazelcastClientFactory.cs
- src/Hazelcast.Net/NetStandard/StreamExtensions.cs
depends on #342 
Temp. make AsyncContext internal - it all works OK but we want to revisit the API.
> Make AsyncContext internal

- src/Hazelcast.Net/Clustering/ClusterConnections.cs
- src/Hazelcast.Net/Clustering/Heartbeat.cs
- src/Hazelcast.Net/Core/GuidExtensions.cs
Fixes #56 - see issue for details
> Logging improvement, better details when a client connects to a server (fix #56)

- doc/dev/doc/atomiclong.md
- doc/dev/doc/cpsubsystem.md
Add documentation for IAtomicLong
> AtomicLong documentation

- src/Hazelcast.Net.Examples/Hazelcast.Net.Examples.csproj
- src/Hazelcast.Net.Testing/Hazelcast.Net.Testing.csproj
- src/Hazelcast.Net.Tests/Hazelcast.Net.Tests.csproj
net462 referances added to Hazelcast.Net.Test, Hazelcast.Net.Examples, Hazelcast.Net.Testing
> Adding new referances

- .gitignore
Ignore ReSharper cache if it's saving to Solution folder: https://www.jetbrains.com/help/resharper/Configuring_Caches_Location.html
> Ignore ReSharper local cache folder

- src/Hazelcast.Net/Clustering/Invocation.cs
Fix bug in invocation retry where we could end up with a negative timeout and crash.
> Fix bug in invocation retry

- src/Hazelcast.Net.Tests/Remote/ReconnectTests.cs
After: #447
Adds a test for issue #429.
> Add Client reconnection test (issue #429)

- src/Hazelcast.Net/Exceptions/ClientOfflineException.cs
- src/Hazelcast.Net/Exceptions/ExceptionMessages.cs
- src/Hazelcast.Net/Exceptions/TargetUnreachableException.cs
- src/Hazelcast.Net/Exceptions/TaskTimeoutException.cs
> Cleanup Core exceptions

- src/Hazelcast.Net.Win32/Hazelcast.Net.Win32.csproj
> Enable SourceLink for Win32, Fix NuGet package [API-410]

- src/Hazelcast.Net.Tests/Configuration/HazelcastOptionsTests.cs
- src/Hazelcast.Net.Tests/Data/DataTests.cs
- src/Hazelcast.Net.Tests/Networking/AddressProviderTests.cs
- src/Hazelcast.Net/Clustering/Authenticator.cs
- src/Hazelcast.Net/Clustering/Cluster.cs
- src/Hazelcast.Net/Clustering/ClusterConnections.cs
- src/Hazelcast.Net/Clustering/ClusterEvents.cs
- src/Hazelcast.Net/Clustering/ClusterMembers.cs
- src/Hazelcast.Net/Clustering/DistributedEventScheduler.cs
- src/Hazelcast.Net/Clustering/Heartbeat.cs
- src/Hazelcast.Net/Clustering/MemberConnection.cs
- src/Hazelcast.Net/Clustering/MemberConnectionQueue.cs
- src/Hazelcast.Net/Clustering/StateChangeQueue.cs
- src/Hazelcast.Net/Clustering/TerminateConnections.cs
- src/Hazelcast.Net/Core/AsyncQueue.cs
- src/Hazelcast.Net/Core/ClientVersion.cs
- src/Hazelcast.Net/Core/EnumExtensions.cs
- src/Hazelcast.Net/Core/HConsoleOptions.cs
- src/Hazelcast.Net/Models/AuthenticationResult.cs
- src/Hazelcast.Net/NearCaching/NearCacheManager.cs
- src/Hazelcast.Net/Networking/AddressProvider.cs
- src/Hazelcast.Net/Networking/CloudOptions.cs
- src/Hazelcast.Net/Partitioning/Partitioner.cs
A set of updates to Cluster code, in preparation for Cloud support implementation.
> Cluster Updates for Cloud [API-311,API-225]

- src/Hazelcast.Net.Examples/Client/LongRunningCloudClient.cs
- src/Hazelcast.Net.Tests/Cloud/CloudTests.cs
- src/Hazelcast.Net.Tests/Resources/Java/CloudTests/Program.java
- src/Hazelcast.Net.Tests/Resources/Java/CloudTests/TestConsumer.java
- src/Hazelcast.Net/Hazelcast.Net.csproj
- src/Hazelcast.Net/HazelcastClient.cs
- src/Hazelcast.Net/HazelcastOptions.cs
- src/Hazelcast.Net/Metrics/ClientMetricSource.cs
- src/Hazelcast.Net/Metrics/DataOutputStream.cs
- src/Hazelcast.Net/Metrics/EnumerableOfMetricsExtensions.cs
- src/Hazelcast.Net/Metrics/IMetricAsyncSource.cs
- src/Hazelcast.Net/Metrics/IMetricDescriptor.cs
- src/Hazelcast.Net/Metrics/IMetricSource.cs
- src/Hazelcast.Net/Metrics/Metric.cs
- src/Hazelcast.Net/Metrics/MetricDescriptor.cs
- src/Hazelcast.Net/Metrics/MetricDescriptorExtensions.cs
- src/Hazelcast.Net/Metrics/MetricUnit.cs
- src/Hazelcast.Net/Metrics/MetricValueType.cs
- src/Hazelcast.Net/Metrics/Metric`TValue.cs
- src/Hazelcast.Net/Metrics/MetricsCompressor.cs
- src/Hazelcast.Net/Metrics/MetricsOptions.cs
- src/Hazelcast.Net/Metrics/MetricsPublisher.cs
- src/Hazelcast.Net/NearCaching/NearCacheBase.cs
- src/Hazelcast.Net/NearCaching/NearCacheManager.cs
- src/Hazelcast.Net/NearCaching/NearCacheStatistics.cs
Implements metrics and all plumbing required for a proper Cloud support.
With this PR, the client can run against Cloud servers and will show with proper metrics in the dashboard (MC).
Should be tested against Cloud.
> Metrics and cloud [API-225]

- src/Hazelcast.Net/Clustering/MemberConnection.cs
> Bugfix/client hang [API-236]

- src/Hazelcast.Net.Examples/Client/KerberosExample.cs
- src/Hazelcast.Net.Examples/Security/ClientSslExample.cs
- src/Hazelcast.Net.Examples/Security/ClientSslMutualAuthExample.cs
- src/Hazelcast.Net.Examples/Security/KerberosExample.cs
Add a minimal Kerberos example to our examples project.
> Add Kerberos example [API-278]

- hz.ps1
- Switch to hazelcast-all package
- Update RC version to 0.8 (optional, can be reverted)
> Hz script update

- src/Hazelcast.Net.Testing/SupportAttribute.cs
- src/Hazelcast.Net.Tests/Remote/ClientMapTest.cs
- src/Hazelcast.Net.Tests/Support/Issue501.cs
- src/Hazelcast.Net/Core/HConsoleOptions.cs
- src/Hazelcast.Net/DistributedObjects/MapEntryRemovedEventHandler.cs
> Fix missing old value in map events

- src/Hazelcast.Net.Tests/Remote/ClientMapTest.cs
- src/Hazelcast.Net/Query/InPredicate.cs
- src/Hazelcast.Net/Query/Predicates.cs
> Bugfix Predicates.In

- doc/dev/doc/download-install.md
- doc/dev/doc/getting-started.md
Depends on #510
This addresses #469 by revisiting our dependencies and/or documenting the required binding redirects for .NET Framework.
> Cleanup "DLL Hell"

- src/Hazelcast.Net.Examples/Sql/SqlBasicQueryExample.cs
- src/Hazelcast.Net.Examples/Sql/SqlLinqEnumerationExample.cs
Missing part to query over a map is added to SQL examples.
> map creating  command added

- src/Hazelcast.Net.Tests/Sql/SqlQueryResultTests.cs
- src/Hazelcast.Net.Tests/TestObjects/DummyPortable.cs
- src/Hazelcast.Net/Sql/SqlQueryResult.cs
- src/Hazelcast.Net/Sql/SqlRow.cs
Lazy sql deserialization is implemented.
> lazy deserialization impl.

- .github/workflows/jira_trigger.yml
- src/Hazelcast.Net.Tests/Sql/SqlQueryResultTests.cs
- src/Hazelcast.Net/Protocol/CustomCodecs/SqlErrorCodec.cs
- src/Hazelcast.Net/Sql/HazelcastSqlException.cs
- src/Hazelcast.Net/Sql/SqlError.cs
- src/Hazelcast.Net/Sql/SqlRow.cs
suggestion field implemented to sql exception
> suggestion field implemented to sql exception

- doc/dev/doc/distributed-objects/flakeidgenerator.md
- doc/dev/doc/toc.md
Add missing documentation (see issue)
> Add FlakeIdGenerator documentation

- src/Hazelcast.Net.Tests/Networking/AddressProviderTests.cs
- src/Hazelcast.Net.Tests/Networking/NetworkAddressTests.cs
- src/Hazelcast.Net/Clustering/ClusterConnections.cs
- src/Hazelcast.Net/Clustering/ClusterEvents.cs
- src/Hazelcast.Net/Clustering/ClusterMembers.cs
- src/Hazelcast.Net/Clustering/ClusterState.cs
- src/Hazelcast.Net/Models/MemberInfo.cs
- src/Hazelcast.Net/Networking/AddressProvider.cs
- src/Hazelcast.Net/Networking/CloudAddressProviderSource.cs
- src/Hazelcast.Net/Networking/CloudDiscovery.cs
- src/Hazelcast.Net/Networking/ConfigurationAddressProviderSource.cs
- src/Hazelcast.Net/Networking/ConnectAddressResolver.cs
- src/Hazelcast.Net/Networking/IAddressProviderSource.cs
- src/Hazelcast.Net/Networking/NetworkingOptions.cs
> Networking fixes [API-1020]

- src/Hazelcast.Net.Tests/Messaging/ClientMessageTests.cs
- src/Hazelcast.Net.Tests/Sql/SqlSerializationDeserializationTests.cs
This is a very minor PR that only affects 1 test and clarifies what it tests.
> Clarify a test following SQL codecs generation fixes

- hz.ps1
Fix 
* path to the test coverage reports
* java version detection
> hz.ps1 / fixes

- doc/dev/doc/configuration/sources.md
- doc/dev/doc/failover.md
- doc/dev/doc/network.md
Failover docs are added.
Note: these should be picked for master later.
> Failover Docs Added

- src/Hazelcast.Net.Testing/TestUtils.cs
- src/Hazelcast.Net.Tests/Serialization/DataInputOutputTest.cs
- src/Hazelcast.Net.Tests/Serialization/Objects/KitchenSinkDataSerializable.cs
- src/Hazelcast.Net.Tests/Serialization/Objects/KitchenSinkPortable.cs
- src/Hazelcast.Net/Serialization/ObjectDataInput.api.cs
Backport of:
* Read size fixed
* Review changes.
(cherry picked from commit 8c27ae15a973ae86dee0500625b822caaae4f6a2)
> Backport of `ReadStringArray` Fixed and Tests Case Enlarged [API-1413] (#649) to `v4.0.z`

- src/Hazelcast.Net.Testing/TestUtils.cs
- src/Hazelcast.Net.Tests/Serialization/DataInputOutputTest.cs
- src/Hazelcast.Net.Tests/Serialization/Objects/KitchenSinkDataSerializable.cs
- src/Hazelcast.Net.Tests/Serialization/Objects/KitchenSinkPortable.cs
- src/Hazelcast.Net/Serialization/ObjectDataInput.api.cs
Backport of:
* Read size fixed
* Review changes.
(cherry picked from commit 8c27ae15a973ae86dee0500625b822caaae4f6a2)
> Backport of `ReadStringArray` Fixed and Tests Case Enlarged [API-1413] (#649) to `v5.0.z`

- doc/dev/doc/toc.md
- src/Hazelcast.Net/Hazelcast.Net.csproj
- Missing link for failover documentation is added to toc.
- Read file linked to Nuget.
> Documentation Improvements [API-1396] [API-1285]

- Hazelcast.Net.sln.DotSettings
- src/Directory.Build.props
- src/Hazelcast.Net/AssemblySigning.cs
- src/Hazelcast.Net/Hazelcast.Net.csproj
- src/Hazelcast.Net/Messaging/DumpMessagingExtensions.cs
No warnings occurred with the upgrade.
> Upgrade to C# 10 [API-1091]

- src/Hazelcast.Net.Tests/Serialization/Compact/CompactOptionsTests.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/TestObjects.cs
- src/Hazelcast.Net/Core/Symbols.cs
- src/Hazelcast.Net/Serialization/Compact/CompactOptions.cs
- src/Hazelcast.Net/Serialization/Compact/CompactRegistration.cs
- src/Hazelcast.Net/Serialization/Compact/CompactSerializerAdapter.cs
- src/Hazelcast.Net/Serialization/Compact/CompactSerializerExtensions.cs
- src/Hazelcast.Net/Serialization/Compact/ICompactReader.cs
- src/Hazelcast.Net/Serialization/Compact/ICompactSerializer.cs
- src/Hazelcast.Net/Serialization/Compact/ICompactWriter.cs
Introduce compact serialization options + some interfaces required for compact-serialization.
> [compact 7] Compact - Introduce options + some interfaces [API-971]

- src/Hazelcast.Net.Tests/Serialization/Compact/CompactOptionsTests.cs
- src/Hazelcast.Net/Serialization/Compact/CompactOptions.cs
- src/Hazelcast.Net/Serialization/Compact/CompactSerializationSerializer.cs
- src/Hazelcast.Net/Serialization/Compact/CompactSerializationSerializerAdapter.cs
- src/Hazelcast.Net/Serialization/Compact/CompactSerializerAdapter.cs
- src/Hazelcast.Net/Serialization/Compact/CompactSerializerBase.cs
- src/Hazelcast.Net/Serialization/Compact/SchemaBuilderWriter.cs
- src/Hazelcast.Net/Serialization/SerializationConstants.cs
- src/Hazelcast.Net/Serialization/SerializationService.ReadWrite.cs
- src/Hazelcast.Net/Serialization/UnknownCompactSchemaException.cs
Introduce the compact serializer.
> [compact 11] Compact - Introduce serializer [API-971]

- src/Hazelcast.Net/Clustering/Cluster.cs
- src/Hazelcast.Net/Clustering/ClusterMembers.cs
- src/Hazelcast.Net/Clustering/ClusterMessaging.cs
- src/Hazelcast.Net/Clustering/ClusterState.cs
- src/Hazelcast.Net/DistributedObjects/DistributedObjectFactory.cs
- src/Hazelcast.Net/HazelcastClient.cs
A code-cleanup PRs that just cleans things up.
> [compact 12] Misc code cleanup + dist. objects factory [API-971]

- src/Hazelcast.Net/Clustering/Cluster.cs
- src/Hazelcast.Net/HazelcastClient.cs
- src/Hazelcast.Net/HazelcastClientFactory.cs
- src/Hazelcast.Net/Serialization/SerializationOptions.cs
- src/Hazelcast.Net/Serialization/SerializationService.Lookup.cs
- src/Hazelcast.Net/Serialization/SerializationService.ReadWrite.cs
- src/Hazelcast.Net/Serialization/SerializationService.cs
- src/Hazelcast.Net/Serialization/SerializationServiceBuilder.cs
Wire the compact serializer - so now it's available for real!
> [compact 14] Compact - Wire Compact Serializer [API-971]

- src/Hazelcast.Net/Serialization/Compact/CompactOptions.cs
- src/Hazelcast.Net/Serialization/Compact/ReflectionSerializer.cs
This PR implements the reflection serializer which supports total zero-config serialization of objects.
> [compact 15] Compact - Bring in the reflection serializer [API-971]

- src/Hazelcast.Net.Benchmarks/Hazelcast.Net.Benchmarks.csproj
- src/Hazelcast.Net.DependencyInjection/Hazelcast.Net.DependencyInjection.csproj
- src/Hazelcast.Net.DocAsCode/Hazelcast.Net.DocAsCode.csproj
- src/Hazelcast.Net.Examples/Hazelcast.Net.Examples.csproj
- src/Hazelcast.Net.JetBrainsAnnotations/Hazelcast.Net.JetBrainsAnnotations.csproj
- src/Hazelcast.Net.Testing/Hazelcast.Net.Testing.csproj
- src/Hazelcast.Net.Tests/Hazelcast.Net.Tests.csproj
- src/Hazelcast.Net.Tests/Serialization/Compact/CompactSerializationSerializerTests.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/ReaderWriterTests.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/ReflectionHelper.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/ReflectionSerializerTests.cs
- src/Hazelcast.Net.Win32/Hazelcast.Net.Win32.csproj
- src/Hazelcast.Net/DistributedObjects/DistributedObjectFactory.cs
- src/Hazelcast.Net/Hazelcast.Net.csproj
- src/Hazelcast.Net/HazelcastClientFactory.cs
- src/Hazelcast.Net/Networking/AddressProvider.cs
- src/Hazelcast.Net/Serialization/Compact/CompactOptions.cs
- src/Hazelcast.Net/Serialization/Compact/CompactSerializationSerializer.cs
- src/Hazelcast.Net/Serialization/Compact/CompactSerializerAdapter.cs
- src/Hazelcast.Net/Serialization/Compact/ISchemas.cs
- src/Hazelcast.Net/Serialization/Compact/ReflectionSerializer.cs
- src/Hazelcast.Net/Serialization/Compact/Schema.cs
- src/Hazelcast.Net/Serialization/SerializationService.cs
A minor PR that bumps all our NuGet dependencies to a stable state + clears all warnings (except FIXME-related warnings)
> Bump dependency versions, clear some warnings

- hz.ps1
- src/Hazelcast.Net/Core/TaskCoreExtensions.cs
Fix for changes introduced by .NET 7
> Fix for changes introduced by .NET 7

- src/Hazelcast.Net.Tests/Serialization/Compact/CSharpRecordTests.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/ReflectionSerializerTests.cs
- src/Hazelcast.Net/Serialization/Compact/CompactReaderWriterBase.cs
- src/Hazelcast.Net/Serialization/Compact/ReflectionSerializer.cs
This PR adds compact serialization support for C# `record` classes and structs.
> Compact 'record' support [API-1617]

- src/Hazelcast.Net.Tests/Caching/HazelcastCacheTests.cs
- src/Hazelcast.Net.Tests/Core/VerifyTests.cs
- src/Hazelcast.Net.Tests/DotNet/ReflectionTests.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/CompactReaderTests.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/ReflectionDataSource.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/ReflectionSerializerTests.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/SchemaTests.cs
- src/Hazelcast.Net/Core/EnumerableExtensions.cs
- src/Hazelcast.Net/Core/Verify.cs
- src/Hazelcast.Net/Polyfills/StringExtensions.cs
- src/Hazelcast.Net/Serialization/Compact/CompactWriter.cs
- src/Hazelcast.Net/Serialization/Compact/ReflectionSerializer.ReadersWriters.cs
- src/Hazelcast.Net/Serialization/Compact/ReflectionSerializer.cs
> NOTE: depends on #755 
This PR adds compact serialization support for collections such as lists, sets and dictionaries.
> Compact collections support [API-1617]

- src/Hazelcast.Net.Tests/Networking/NetworkingTests.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/CompactOptionsTests.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/SchemaTests.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/SchemasLocalTests.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/SchemasRemoteTests.cs
- src/Hazelcast.Net/Clustering/Cluster.cs
- src/Hazelcast.Net/Clustering/ClusterMessaging.cs
- src/Hazelcast.Net/DistributedObjects/DistributedObjectFactory.cs
- src/Hazelcast.Net/DistributedObjects/Impl/HMap.Setting.cs
- src/Hazelcast.Net/HazelcastClient.cs
- src/Hazelcast.Net/HazelcastClientFactory.cs
- src/Hazelcast.Net/Messaging/ClientMessage.cs
- src/Hazelcast.Net/Messaging/IClusterMessaging.cs
- src/Hazelcast.Net/Models/ICanHaveSchemas.cs
- src/Hazelcast.Net/Protocol/BuiltInCodecs/DataCodec.cs
- src/Hazelcast.Net/Serialization/Compact/CompactOptions.cs
- src/Hazelcast.Net/Serialization/Compact/CompactSerializationSerializer.cs
- src/Hazelcast.Net/Serialization/Compact/ISchemas.cs
- src/Hazelcast.Net/Serialization/Compact/Schemas.cs
- src/Hazelcast.Net/Serialization/HeapData.cs
- src/Hazelcast.Net/Serialization/ObjectDataOutput.cs
- src/Hazelcast.Net/Serialization/SerializationService.ReadWrite.cs
- src/Hazelcast.Net/Serialization/SerializationService.cs
> NOTE: depends on #756 
This PR refactors how schemas are replicated as per the changes in Java.
> Compact schema distrib [API-1617]

- src/Hazelcast.Net.Linq.Async/MapEntry.cs
- src/Hazelcast.Net.Testing/Conditions/ServerVersion.cs
- src/Hazelcast.Net.Testing/HazelcastTestBase.cs
- src/Hazelcast.Net.Testing/JavaRun.cs
- src/Hazelcast.Net.Testing/RemoteControllerClientExtensions.cs
- src/Hazelcast.Net.Testing/ServerVersionDetector.cs
- src/Hazelcast.Net.Tests/Serialization/Compact/FingerprintTests.cs
- src/Hazelcast.Net.Tests/Support/Issue764.cs
- src/Hazelcast.Net/Serialization/Compact/Schema.cs
> Compact Serialization schema not found [API-1801]

- src/Hazelcast.Net.Tests/Serialization/Compact/FingerprintTests.cs
- src/Hazelcast.Net.Tests/Support/Issue764.cs
- src/Hazelcast.Net/Serialization/Compact/CompactReaderWriterBase.cs
- src/Hazelcast.Net/Serialization/Compact/Schema.cs
- src/Hazelcast.Net/Serialization/Compact/SchemaField.cs
Fixes new issue reported in #764.
> Fix Compact Serialization schema errors [API-1801]

- src/Hazelcast.Net/Core/ReadOptimizedLruCache.cs
@ihsandemir caught a case where two threads can evict at the same time. The PR has better synchronization solution to avoid from the case.
> More Reliable Concurrency on Read Optimized LRU cache.

- hz.ps1
Update server version on tests.
> Update Server Version

- hz.ps1
- src/Directory.Build.props
Updated test server and client versions after 5.4.0 release.
> Update Server and Client Versions

- doc/dev/doc/failover.md
Mentioned usage of `ClusterConnectionTimeoutMilliseconds` while usinf failover client.
> Update Blue/Green - Failover Docs [API-2212]

- .github/workflows/build-and-test.yml
> Fix Version of Artifact Upload Action

- build/build.proj
The condition fixed for ubuntu env. Tested via `wsl` on ubuntu-24.04.
> Fix `dotcover` condition

- hz.ps1
- src/Hazelcast.Net.Tests/Core/ClientVersionTests.cs
Backport of https://github.com/hazelcast/hazelcast-csharp-client/pull/970
> Backport of Remove Unnecessary Assertion on Client Version Tests & Upgrade Server Test Version #970 to `5.5.z`

- hz.ps1
Backport of https://github.com/hazelcast/hazelcast-csharp-client/pull/973
> Backport of Fix Hazelcast Patch Releases JAR Downloads to `5.5.z`

- hz.ps1
Backport of https://github.com/hazelcast/hazelcast-csharp-client/pull/975
> Backport of Fix EE Downloads for Patch Versions #975

- hz.ps1
Script now downloads the patch releases from EE repo after `5.4.0`
> Fix EE Downloads for Patch Versions

- src/Hazelcast.Net.Examples/Client/CloudClientExample.cs
- src/Hazelcast.Net.Examples/Client/LongRunningCloudClient.cs
- src/Hazelcast.Net.Testing/CloudTestBase.cs
- src/Hazelcast.Net.Tests/Cloud/ServerlessCloudTests.cs
- src/Hazelcast.Net.Tests/Configuration/HazelcastOptionsTests.cs
- src/Hazelcast.Net/Networking/CloudOptions.cs
chore: rename viridian to hazelcast cloud
> HZC-7235: rename-viridian-to-hazelcast-cloud

- .github/actions/install/action.yml
- build/build.proj
- hz.ps1
- src/Hazelcast.Net.Caching/Hazelcast.Net.Caching.csproj
- src/Hazelcast.Net.DependencyInjection/Hazelcast.Net.DependencyInjection.csproj
- src/Hazelcast.Net.Examples/Hazelcast.Net.Examples.csproj
- src/Hazelcast.Net.Linq.Async/Hazelcast.Net.Linq.Async.csproj
- src/Hazelcast.Net.Tests/Hazelcast.Net.Tests.csproj
- src/Hazelcast.Net.Win32/Hazelcast.Net.Win32.csproj
- src/Hazelcast.Net/Hazelcast.Net.csproj
The PR depends on https://github.com/hazelcast/hazelcast-csharp-client/pull/989
> Add .NET 9 Support [API-2271]
